//------------------------------------------------------------------------------
// <auto-generated>
//    This code was generated from a template.
//
//    Manual changes to this file may cause unexpected behavior in your application.
//    Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace MVC_BasedFoodOrderingSystem.Models
{
    using System;
    using System.Data.Entity;
    using System.Data.Entity.Infrastructure;
    
    public partial class FoodDataEntities : DbContext
    {
        public FoodDataEntities()
            : base("name=FoodDataEntities")
        {
        }
    
        protected override void OnModelCreating(DbModelBuilder modelBuilder)
        {
            throw new UnintentionalCodeFirstException();
        }
    
        public DbSet<TblContact> TblContacts { get; set; }
        public DbSet<TblRegister> TblRegisters { get; set; }
        public DbSet<TblRequest> TblRequests { get; set; }
    }
}
