//------------------------------------------------------------------------------
// <auto-generated>
//    This code was generated from a template.
//
//    Manual changes to this file may cause unexpected behavior in your application.
//    Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace MVC_BasedFoodOrderingSystem.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class TblRequest
    {
        public string uName { get; set; }
        public System.DateTime orderDate { get; set; }
        public string foodCat { get; set; }
        public string foodName { get; set; }
        public int qty { get; set; }
        public string description { get; set; }
    }
}
